FROM python:3.12-alpine
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk add --no-cache build-base

COPY requirements/prod.txt requirements/base.txt /app/requirements/
RUN pip install -r requirements/prod.txt
ENV DJANGO_SETTINGS_MODULE=config.settings.prod

COPY . .

EXPOSE 8000

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]